apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-b0fw
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-b0fw
    app.kubernetes.io/part-of: tkrw-pr712-0075-0001-app
  name: devfile-sample-b0fw
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-b0fw
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-b0fw
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0001-tenant/tkrw-pr712-0075-0001-app/devfile-sample-b0fw@sha256:7d00b5c4ed214a1defb45f3906e40169b058e277f99b9911516a38e84fddf843
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
